#!/usr/bin/env bash
#
# Scaffold a full CRUD domain resource end to end, following docs/CONVENTIONS.md:
#   - src/domain/<Entity>.hpp            (struct + from_row + to_json)
#   - src/repositories/<Entity>Repository.hpp  (typed exceptions + find/list/count/create/remove)
#   - src/api/<Entity>sController.hpp     (list/create/get/delete, admin-gated, with_repo_errors)
#   - wires the #include into src/api/Api.hpp
#   - adds the routes to Api::get_endpoints() in src/api/Endpoints.hpp
#   - appends a path + schema block to docs/openapi.yaml
#   - tests/integration/test_<entity>.cpp skeleton
#
# The generated code COMPILES as-is with a minimal {id, name, created_at}
# shape — edit the three files to add your real columns (keep struct /
# from_row / to_json / SQL in sync), then add the migration with
# scripts/new-migration.sh and the bucket-filter entry (check-test-buckets.sh
# tells you where).
#
# Usage:
#   ./scripts/new-resource.sh <Entity>            # singular PascalCase, e.g. Product
#   ./scripts/new-resource.sh Product
#
set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <Entity>   (singular PascalCase, e.g. Product)" >&2
    exit 2
fi

ENTITY="$1"
if [[ ! "$ENTITY" =~ ^[A-Z][A-Za-z0-9]+$ ]]; then
    echo "ERROR: entity must be PascalCase (e.g. Product), got '$ENTITY'" >&2
    exit 2
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# Derivations: lower-case singular, naive plural (append s), table = plural.
LOWER="$(printf '%s' "$ENTITY" | tr '[:upper:]' '[:lower:]')"
PLURAL="${LOWER}s"
ROUTE="/api/${PLURAL}"
CONTROLLER="${ENTITY}sController"

DOMAIN_FILE="$ROOT/src/domain/${ENTITY}.hpp"
REPO_FILE="$ROOT/src/repositories/${ENTITY}Repository.hpp"
CTRL_FILE="$ROOT/src/api/${CONTROLLER}.hpp"
TEST_FILE="$ROOT/tests/integration/test_${LOWER}.cpp"
API_HPP="$ROOT/src/api/Api.hpp"
ENDPOINTS_HPP="$ROOT/src/api/Endpoints.hpp"
OPENAPI="$ROOT/docs/openapi.yaml"

for f in "$DOMAIN_FILE" "$REPO_FILE" "$CTRL_FILE"; do
    if [[ -e "$f" ]]; then
        echo "ERROR: $f already exists — refusing to overwrite" >&2
        exit 1
    fi
done

# ── 1. Domain DTO ───────────────────────────────────────────────────────
cat >"$DOMAIN_FILE" <<EOF
/**
 * @file ${ENTITY}.hpp
 * @brief ${ENTITY} domain model. Generated by scripts/new-resource.sh.
 *
 * Add your real columns below — keep the struct, from_row() and to_json()
 * in sync (each field appears in all three). Never serialize secrets in
 * to_json (see tests/unit/test_domain_serialization.cpp).
 */

#pragma once

#include <string>

#include <pqxx/pqxx>

#include <nlohmann/json.hpp>

namespace Domain {

struct ${ENTITY} {
    std::string id;          // UUID v4 (text)
    std::string name;        // TODO: replace with your real columns
    std::string created_at;

    template <typename Row>
    static ${ENTITY} from_row(const Row& row) {
        ${ENTITY} e;
        e.id = row["id"].template as<std::string>();
        e.name = row["name"].template as<std::string>();
        e.created_at = row["created_at"].template as<std::string>();
        return e;
    }
};

inline void to_json(nlohmann::json& j, const ${ENTITY}& e) {
    j = nlohmann::json{
        {"id", e.id},
        {"name", e.name},
        {"created_at", e.created_at},
    };
}

}  // namespace Domain
EOF
echo "==> Created $DOMAIN_FILE"

# ── 2. Repository ───────────────────────────────────────────────────────
cat >"$REPO_FILE" <<EOF
/**
 * @file ${ENTITY}Repository.hpp
 * @brief All SQL touching \`${PLURAL}\` lives here. Generated by
 *        scripts/new-resource.sh. Controllers never touch pqxx directly.
 */

#pragma once

#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

#include <pqxx/pqxx>

#include "database/Database.hpp"
#include "domain/${ENTITY}.hpp"
#include "repositories/SqlErrors.hpp"

namespace Repositories {

struct Duplicate${ENTITY} : std::runtime_error {
    Duplicate${ENTITY}() : std::runtime_error("${LOWER} already exists") {}
};

struct ${ENTITY}NotFound : std::runtime_error {
    ${ENTITY}NotFound() : std::runtime_error("${LOWER} not found") {}
};

class ${ENTITY}Repository {
public:
    static constexpr const char* kColumns = "id, name, created_at";

    std::optional<Domain::${ENTITY}> find(const std::string& id) {
        return Database::get().execute_read([&](auto& txn) -> std::optional<Domain::${ENTITY}> {
            auto r = txn.exec_params(std::string("SELECT ") + kColumns + " FROM ${PLURAL} WHERE id = \$1", id);
            if (r.empty())
                return std::nullopt;
            return Domain::${ENTITY}::from_row(r[0]);
        });
    }

    std::vector<Domain::${ENTITY}> list(int limit = 50, int offset = 0) {
        return Database::get().execute_read([&](auto& txn) {
            auto r = txn.exec_params(
                std::string("SELECT ") + kColumns + " FROM ${PLURAL} ORDER BY created_at DESC LIMIT \$1 OFFSET \$2",
                limit, offset);
            std::vector<Domain::${ENTITY}> out;
            out.reserve(r.size());
            for (const auto& row : r)
                out.push_back(Domain::${ENTITY}::from_row(row));
            return out;
        });
    }

    long count() {
        return Database::get().execute_read([&](auto& txn) {
            auto r = txn.exec("SELECT COUNT(*) FROM ${PLURAL}");
            return r[0][0].template as<long>();
        });
    }

    Domain::${ENTITY} create(const std::string& name) {
        return detail::translate_sql(
            [&] {
                return Database::get().execute_write([&](auto& txn) {
                    auto r = txn.exec_params(
                        std::string("INSERT INTO ${PLURAL} (name) VALUES (\$1) RETURNING ") + kColumns, name);
                    return Domain::${ENTITY}::from_row(r[0]);
                });
            },
            [](std::string_view ss) {
                if (ss == "23505")
                    throw Duplicate${ENTITY}{};
            });
    }

    void remove(const std::string& id) {
        Database::get().execute_write([&](auto& txn) {
            auto r = txn.exec_params("DELETE FROM ${PLURAL} WHERE id = \$1 RETURNING id", id);
            if (r.empty())
                throw ${ENTITY}NotFound{};
            return 0;
        });
    }
};

}  // namespace Repositories
EOF
echo "==> Created $REPO_FILE"

# ── 3. Controller ───────────────────────────────────────────────────────
cat >"$CTRL_FILE" <<EOF
/**
 * @file ${CONTROLLER}.hpp
 * @brief ${ENTITY} CRUD endpoints. Generated by scripts/new-resource.sh.
 *        Admin-gated; follows docs/CONVENTIONS.md.
 */

#pragma once

#include <drogon/HttpController.h>
#include <drogon/drogon.h>

#include <nlohmann/json.hpp>

#include "api/Guards.hpp"
#include "api/HandlerSupport.hpp"
#include "api/RequestUtils.hpp"
#include "api/Validation.hpp"
#include "domain/${ENTITY}.hpp"
#include "repositories/${ENTITY}Repository.hpp"
#include "utils/ErrorResponse.hpp"

namespace Api {

using namespace drogon;
using json = nlohmann::json;

class ${CONTROLLER} : public HttpController<${CONTROLLER}> {
public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(${CONTROLLER}::list${ENTITY}s, "${ROUTE}", Get);
    ADD_METHOD_TO(${CONTROLLER}::create${ENTITY}, "${ROUTE}", Post);
    ADD_METHOD_TO(${CONTROLLER}::get${ENTITY}, "${ROUTE}/{1}", Get);
    ADD_METHOD_TO(${CONTROLLER}::delete${ENTITY}, "${ROUTE}/{1}", Delete);
    METHOD_LIST_END

    void list${ENTITY}s(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        API_REQUIRE_ADMIN(req, callback);
        const auto page = parse_page_params(req, /*default_limit=*/50, /*max_limit=*/200);
        Repositories::${ENTITY}Repository repo;
        auto items = repo.list(page.limit, page.offset);
        long total = repo.count();
        json data = json::array();
        for (const auto& e : items)
            data.push_back(e);
        callback(Response::ok({{"data", data}, {"total", total}, {"limit", page.limit}, {"offset", page.offset}}));
    }

    void create${ENTITY}(const HttpRequestPtr& req, std::function<void(const HttpResponsePtr&)>&& callback) {
        API_REQUIRE_ADMIN(req, callback);
        json body;
        if (!Validation::parse_body(req, body, callback)) return;
        Validation::Errors errs;
        Validation::require(errs, body, "name");
        Validation::string_length(errs, body, "name", 1, 255);
        if (errs.any()) {
            callback(Validation::response_400(errs));
            return;
        }
        with_repo_errors(callback, "create${ENTITY}", [&] {
            Repositories::${ENTITY}Repository repo;
            auto created = repo.create(body["name"].get<std::string>());
            auto resp = Response::ok({{"data", json(created)}});
            resp->setStatusCode(k201Created);
            callback(resp);
        });
    }

    void get${ENTITY}(const HttpRequestPtr& req,
                      std::function<void(const HttpResponsePtr&)>&& callback,
                      const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!is_valid_uuid(id)) {
            callback(ErrorResponse::bad_request("invalid_uuid", "UUID format is invalid"));
            return;
        }
        Repositories::${ENTITY}Repository repo;
        auto found = repo.find(id);
        if (!found) {
            callback(ErrorResponse::not_found("${LOWER}"));
            return;
        }
        callback(Response::ok({{"data", json(*found)}}));
    }

    void delete${ENTITY}(const HttpRequestPtr& req,
                         std::function<void(const HttpResponsePtr&)>&& callback,
                         const std::string& id) {
        API_REQUIRE_ADMIN(req, callback);
        if (!is_valid_uuid(id)) {
            callback(ErrorResponse::bad_request("invalid_uuid", "UUID format is invalid"));
            return;
        }
        with_repo_errors(callback, "delete${ENTITY}", [&] {
            Repositories::${ENTITY}Repository repo;
            repo.remove(id);
            callback(Response::ok({{"message", "${ENTITY} deleted"}}));
        });
    }
};

}  // namespace Api
EOF
echo "==> Created $CTRL_FILE"

# ── 4. Wire #include into Api.hpp ───────────────────────────────────────
if ! grep -q "#include \"api/${CONTROLLER}.hpp\"" "$API_HPP"; then
    awk -v inc="#include \"api/${CONTROLLER}.hpp\"" '
        /#include "api\/JobsController.hpp"/ { print; print inc; next }
        { print }
    ' "$API_HPP" >"$API_HPP.tmp" && mv "$API_HPP.tmp" "$API_HPP"
    echo "==> Added #include to $API_HPP"
fi

# ── 5. Routes into get_endpoints() (Endpoints.hpp) ──────────────────────
add_route() {
    local method="$1" path="$2" desc="$3"
    local row="        {\"${method}\", \"${path}\", \"${desc}\"},"
    if grep -qF "\"${method}\", \"${path}\"" "$ENDPOINTS_HPP"; then return; fi
    awk -v row="$row" '
        /^    };$/ && !done && seen { print row; done=1 }
        /inline const std::vector<EndpointInfo>& get_endpoints/ { seen=1 }
        { print }
    ' "$ENDPOINTS_HPP" >"$ENDPOINTS_HPP.tmp" && mv "$ENDPOINTS_HPP.tmp" "$ENDPOINTS_HPP"
    if ! grep -qF "\"${method}\", \"${path}\"" "$ENDPOINTS_HPP"; then
        echo "ERROR: failed to insert route ${method} ${path} into Endpoints.hpp — add by hand" >&2
        exit 1
    fi
}
add_route "GET" "${ROUTE}" "List ${PLURAL}"
add_route "POST" "${ROUTE}" "Create ${LOWER}"
add_route "GET" "${ROUTE}/{id}" "Get ${LOWER}"
add_route "DELETE" "${ROUTE}/{id}" "Delete ${LOWER}"
echo "==> Added 4 routes to $ENDPOINTS_HPP"

# ── 6. OpenAPI block ────────────────────────────────────────────────────
if ! grep -q "^  ${ROUTE}:" "$OPENAPI"; then
    cat >>"$OPENAPI" <<EOF

  ${ROUTE}:
    get:
      summary: List ${PLURAL} (admin; offset-paginated)
      tags: [${PLURAL}]
      security: [{ BearerAuth: [] }]
      parameters:
        - { name: limit,  in: query, schema: { type: integer, minimum: 1, maximum: 200, default: 50 } }
        - { name: offset, in: query, schema: { type: integer, minimum: 0, default: 0 } }
      responses:
        '200': { description: "{ data, total, limit, offset }" }
        '403': { description: Not an admin }
    post:
      summary: Create ${LOWER} (admin)
      tags: [${PLURAL}]
      security: [{ BearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name]
              properties: { name: { type: string, minLength: 1, maxLength: 255 } }
      responses:
        '201': { description: Created }
        '400': { description: Validation failed }
        '403': { description: Not an admin }
        '409': { description: Already exists }
  ${ROUTE}/{id}:
    parameters:
      - { name: id, in: path, required: true, schema: { type: string, format: uuid } }
    get:
      summary: Get ${LOWER} (admin)
      tags: [${PLURAL}]
      security: [{ BearerAuth: [] }]
      responses:
        '200': { description: OK }
        '404': { description: Not found }
    delete:
      summary: Delete ${LOWER} (admin)
      tags: [${PLURAL}]
      security: [{ BearerAuth: [] }]
      responses:
        '200': { description: Deleted }
        '404': { description: Not found }
EOF
    echo "==> Appended OpenAPI block to $OPENAPI"
fi

# ── 7. Integration test skeleton ────────────────────────────────────────
if [[ ! -e "$TEST_FILE" ]]; then
    cat >"$TEST_FILE" <<EOF
/**
 * @file test_${LOWER}.cpp
 * @brief Integration tests for ${CONTROLLER}. Generated by new-resource.sh.
 *        Fill in once the migration + real columns exist.
 *
 * NB: ${ENTITY}sFlowTest is a NEW suite — add it to the integration bucket
 * filter (Makefile INTEGRATION_FILTER + CMakeLists + CI), or
 * scripts/check-test-buckets.sh will fail. It needs a '${PLURAL}' table.
 */

#include <gtest/gtest.h>

#include <nlohmann/json.hpp>

#include "api/${CONTROLLER}.hpp"
#include "test_helpers.hpp"

using json = nlohmann::json;
using namespace drogon;

namespace {

class ${ENTITY}sFlowTest : public TestHelpers::CoreBackedTest {
protected:
    Api::${CONTROLLER} controller;
    std::string config_file_name() const override { return "${LOWER}_flow_test_config.json"; }
    void config_overrides(json& cfg) override {
        cfg["database"]["migrations_enabled"] = true;
        cfg["database"]["migrations_dir"] = "migrations";
    }
};

TEST_F(${ENTITY}sFlowTest, ListReturnsEnvelope) {
    HttpResponsePtr resp;
    controller.list${ENTITY}s(TestHelpers::make_request(Get), [&](const HttpResponsePtr& r) { resp = r; });
    ASSERT_NE(resp, nullptr);
    // With AUTH_MODE=none the admin guard is a no-op, so this reaches the handler.
    EXPECT_EQ(resp->statusCode(), k200OK);
    auto body = json::parse(std::string(resp->body()));
    EXPECT_TRUE(body.contains("data"));
    EXPECT_TRUE(body.contains("total"));
}

}  // namespace
EOF
    echo "==> Created $TEST_FILE"
fi

# ── 8. Migration (CREATE TABLE + updated_at trigger) ────────────────────
# Co-generate the table the repo/DTO above reference, so the scaffold is not
# left pointing at a non-existent table. new-migration.sh --table emits the
# stub shape (id/name/created_at/updated_at) plus a trigger wired to the shared
# touch_updated_at() from migrations/000_updated_at_trigger.sql.
if grep -rqE "name[ '\"]*=*[ '\"]*${PLURAL}_table" "$ROOT/migrations" 2>/dev/null ||
    find "$ROOT/migrations" -maxdepth 1 -name "*_${PLURAL}*.sql" | grep -q .; then
    echo "==> Migration for '${PLURAL}' already exists — skipping"
else
    "$ROOT/scripts/new-migration.sh" "add_${PLURAL}_table" --table "${PLURAL}"
fi

cat <<EOF

Done. Next steps (manual):
  1. Edit src/domain/${ENTITY}.hpp + ${ENTITY}Repository.hpp for your real
     columns, then mirror them in the generated migration (the table ships
     with the stub {id, name, created_at, updated_at} shape).
  2. Add ${ENTITY}sFlowTest to the integration bucket filter (run
     ./scripts/check-test-buckets.sh — it lists the 5 places, or fails CI).
  3. Frontend: types via 'make frontend-gen-api', page under src/pages/admin/.
  4. Verify:  ./scripts/check-openapi-drift.sh  &&  make test
EOF
